version: "3.3"

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.whoami.rule: "Host(`${HOST}`) && PathPrefix(`/whoami`)"
      #traefik.http.routers.whoami.rule: "Host(`${HOST}`)"
      traefik.http.routers.whoami.middlewares: "whoami-stripprefix"
      traefik.http.routers.whoami.service: "whoami-whoami"
      traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes: "/whoami"
      traefik.http.routers.whoami.entrypoints: "websecure"
      traefik.http.routers.whoami.tls: "true"

networks:
  proxy:
    external: true
