[[tls.certificates]]
  certFile = "/certs/dgdockerx.grinnell.edu.cert"
  keyFile = "/certs/dgdockerx.grinnell.edu.key"

[[tls.certificates]]
  certFile = "/certs/dg-staging.grinnell.edu.cert"
  keyFile = "/certs/dg-staging.grinnell.edu.key"

#
# [[tls.certificates]]
#   certFile = "/certs/static.grinnell.edu.cert"
#   keyFile = "/certs/static.grinnell.edu.key"
#
# [[tls.certificates]]
#   certFile = "/certs/rootstalk.grinnell.edu.cert"
#   keyFile = "/certs/rootstalk.grinnell.edu.key"
